### ISSUE TITLE
그리기 오류

### ISSUE THREAD

**Issue by 1-EXON** [choshinyoung/ImNotGoodAtDrawingButCoding#2]
프로그램을 실행하고 사진을 선택해 그림을 그릴려고 버튼을 클릭하니
프로그램 창이 아닌 곳에 마우스 클릭을 하네요.

**Comment by minibox724** [comment]
![image](https://user-images.githubusercontent.com/61264156/88912754-b6175380-d29a-11ea-8048-0b06767c7733.png)
이런식으로 마우스를 그릴곳에 올려두고 해야해요
